### ISSUE TITLE
Version 7.04 has stopped working with NordVPN on Kodi

### ISSUE THREAD

**Issue by totarello91** [Zomboided/service.vpn.manager#438]
I paste the log:

2025-11-05 20:38:35 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
2025-11-05 20:38:35 WARNING: file '/home/osmc/.kodi/addons/service.vpn.manager/NordVPN/pass.txt' is group or others accessible
2025-11-05 20:38:35 OpenVPN 2.5.1 arm-unknown-linux-gnueabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Aug 25 2025
2025-11-05 20:38:35 library versions: OpenSSL 1.1.1w  11 Sep 2023, LZO 2.10
2025-11-05 20:38:35 Error reading username from Auth authfile: /home/osmc/.kodi/addons/service.vpn.manager/NordVPN/pass.txt
2025-11-05 20:38:35 Exiting due to fatal error

**Comment by peno64** [comment]
I would try to generate a new token and use that one. Maybe it was expired. Make sure that you check that it may not expire.

**Comment by zygolux** [comment]
Same issue. I tried a new token with no luck.
I also tried to re-install the addon from scratch and run the wizard. It gets stuck when trying to "connect using profile"

**Comment by dsgdesign** [comment]
Same here. Spent the last hour trying to troubleshoot. Regenerated new tokens, deactivated-uninstalled-reinstalled service.vpn.manager app. Still same error message as the above post. I'm starting to suspect that NordVPN may have changed something on their end...

**Comment by jamakal** [comment]
I've worked out what's wrong - it appears as though NordVPN have dropped support for the Authorization header in the format 'Authorization: token:<token>' in favour of 'Authorization: Bearer token:<token>'. Tested and it works for me.

This is the same way that the NordVPN Linux client authenticates: https://github.com/NordSecurity/nordvpn-linux/blob/ac46cb609d93fff68cfb8c46bf2d0d835a378cb1/request/request.go#L59

I've raised a PR (https://github.com/Zomboided/service.vpn.manager/pull/439) if we can get it merged @Zomboided!

**Comment by zygolux** [comment]
Thank you so much @jamakal 
I have updated the alternativeNord.py file manually on my Pi and can enjoy again my favorite shows.

**Comment by callerpj** [comment]
Hmm. I changed the alternativeNord.py but still does not work.
any hints?
Thanks in advance

**Comment by CRL901** [comment]
@zygolux  would you mind posting your working alternativeNORD.py file?

**Comment by zygolux** [comment]
> [@zygolux](https://github.com/zygolux) would you mind posting your working alternativeNORD.py file?

I have made the changes mentioned here: https://github.com/Zomboided/service.vpn.manager/pull/439/files

The other things I have done, but I think it did not help at all, and was part of my attempt to understand the issue: get a new token, and reinstall the addon from the zip.

But again the solution comes from @jamakal  and I have done the changes myself on my install, instead of waiting for them to be released.

**Comment by philipp369** [comment]
I am on version 7.0.3 and have the same issue connecting to NordVPN. It started yesterday. I have no way to get to the configuration files. Will you issue a new release?

**Comment by peno64** [comment]
[I also implemented the change from @jamakal and it works without a problem.
You only need to change /libs/alternativeNord.py, that is all. No new token must be generated.
Attached the changed file. So just replace it and restart kodi and it should be fixed.

[alternativeNord.py](https://github.com/user-attachments/files/23396939/alternativeNord.py)

**Comment by peno64** [comment]
Btw, great work @jamakal 
Thx

**Comment by peno64** [comment]
For people not knowing how to update this file you can also do the following. 

- Go to https://github.com/jamakal/service.vpn.manager/tree/master
- Click Code, Download zip
- In kodi, choose "Install from zip"
- Choose this downloaded zip file
- Done

Best to restart kodi after this.

**Comment by philipp369** [comment]
Fab. It worked. Thank you!

**Comment by BadIDMan** [comment]
@jamakal - Great job done!
I can imagine to find the reason why it stopped working isn't obvious, right? But still you were able to do that.
Thanks. It works.

**Comment by dsgdesign** [comment]
Thank you @jamakal. Excellent work and quick resolution! The changes implemented to the alternativeNord.py make NordVPN functional again.

**Comment by vansman2000** [comment]
I did this and after restarting it said nordvpn requires user name and password now. I entered it and its still not working.

**Comment by vansman2000** [comment]
> I did this and after restarting it said nordvpn requires user name and password now. I entered it and its still not working.

Sorry guys. Apparently I had an old .zip file with the same name on my pc. So I put the wrong one in there. Once I put the correct one in it worked like a charm.

**Comment by callerpj** [comment]
Thank you @jamakal . I had to uninstall, new install and create a new token.
😊 
Super work

**Comment by Rotentilaltondt** [comment]
Excellent! Many thanks for your help. I chatted with NordVPN support for an hour yesterday when I also experienced that the VPN was not working. Of course they had no idea what the problem was. I have just sent them the link to the solution outlined here.👍

**Comment by BadIDMan** [comment]
> Excellent! Many thanks for your help. I chatted with NordVPN support for an hour yesterday when I also experienced that the VPN was not working. Of course they had no idea what the problem was. I have just sent them the link to the solution outlined here.👍

Yeah, I created a case for the support and got of course template response that I should perform nonsense steps and provide answer for nonsense questions.
I asked to close the case and also added my comment:

"_It is you who cause this issue by changing your API frontend dropping support for the Authorization header from 'Authorization: token:' format to 'Authorization: Bearer token:'
As a professional company you should announce such changes!
Pass my message to responsible teams.
In case you do similar change in your systems without informing your customers, including me, I will do not renew subscription of your products.
Is it clear to you what you need to do?_"

But for sure they will not care.

**Comment by lemondexter** [comment]
This worked for me. I just used the file posted by Peno64. No need to get new token or change anything else. Spent hours on this. Thanks guys!

**Comment by FruitMachine** [comment]
Thanks for the work to fix

**Comment by gembrite** [comment]
Thanks @jamakal & @peno64 
Fixes the problem perfectly!

**Comment by russhackelford** [comment]
Thank you @jamakal & @peno64   It worked!...Life is good again!

**Comment by Eddy226** [comment]
Many thanks for this fix and long life to OpenVPN !

**Comment by DijieCH** [comment]
Thank you @jamakal & @peno64 It worked!

**Comment by giuseppelarosa** [comment]
Thanks for the fix!
I was getting crazy. I tried everything.

**Comment by shinkathe** [comment]
Here's how to do it for LibreElec or an environment where all you have is SSH and no browsers:

```
ssh root@<kodi-ip>
cd /storage/.kodi/addons/service.vpn.manager/libs
# make backup
cp -a alternativeNord.py alternativeNord.py.bak
# get fixed version on top of existing
wget -O alternativeNord.py https://raw.githubusercontent.com/jamakal/service.vpn.manager/master/libs/alternativeNord.py
#restart kodi
systemctl restart kodi
```

**Comment by Rotentilaltondt** [comment]
> Here's how to do it for libreelec:
> 
> ```
> ssh root@<kodi-ip>
> cd /storage/.kodi/addons/service.vpn.manager/libs
> # make backup
> cp -a alternativeNord.py alternativeNord.py.bak
> # get fixed version on top of existing
> wget -O alternativeNord.py https://raw.githubusercontent.com/jamakal/service.vpn.manager/master/libs/alternativeNord.py
> #restart kodi
> systemctl restart kodi
> ```
Does your suggestion provide a better solution than what has already been suggested by others, and which already works? I'm just asking out of curiosity.

**Comment by shinkathe** [comment]
> Does your suggestion provide a better solution than what has already been suggested by others, and which already works? I'm just asking out of curiosity.

It is simply another means to the same end, which I wanted to provide as a convenience for those who run Kodi in a network box of some kind, in a LibreElec type install where you don't have a browser. Not better, just alternate. 

The best is ofc, when the PR actually gets merged.

**Comment by Jonathan07181** [comment]
Thanks for the zip but Since I installed this zip I can no longer use my remote control in CEC. Is this normal?

**Comment by demers** [comment]
Thanks to @jamakal for the change for NordVPN.  But I had a similar problem with other VPN like 1and1, Surfshark, and Mullvad.  The correction should be made on code for all VPN (not only NordVPN).  Thanks!

**Comment by peno64** [comment]
@demers This was wa specific NordVPN problem because they changed their API header security token.
It has nothing to do with the other providers.
And if these would also fail I guess alot more issue would be posted here so I think your problem is specific *your* problem.

**Comment by Rotentilaltondt** [comment]
> For people not knowing how to update this file you can also do the following.
> 
> * Go to https://github.com/jamakal/service.vpn.manager/tree/master
> * Click Code, Download zip
> * In kodi, choose "Install from zip"
> * Choose this downloaded zip file
> * Done
> 
> Best to restart kodi after this.

For people not knowing how to update this file you can also do the following.

Go to https://github.com/jamakal/service.vpn.manager/tree/master
Click Code, Download zip
- "If.a Linux OS Kodi device (without browser), SSH the zip file to the Kodi device storage".
In kodi, choose "Install from zip"
Choose this downloaded zip file
Done
Best to restart kodi after this.

Again, thank you so much @peno64 and @jamakal

**Comment by JSP6668** [comment]
Hi All,

tried everthing above, but cannot get it to work on OSMC Vero, I assume its somthing OSMC specific, however it is still the same
error in the log, that the username and PW not found in pass.txt.

Any Ideas?

Best regards
Steffen

**Comment by Napsty** [comment]
> Hi All,
> 
> tried everthing above, but cannot get it to work on OSMC Vero, I assume its somthing OSMC specific, however it is still the same error in the log, that the username and PW not found in pass.txt.
> 
> Any Ideas?
> 
> Best regards Steffen

I also use the OSMC Vero and got it working fine. Just needs a manual fix. https://www.geekersdigest.com/how-to-use-nordvpn-in-kodi-on-osmc-or-libreelec-devices/

**Comment by peno64** [comment]
@Napsty 
What manual fix do you exactly mean? The one that is described in this thread I suppose? Because the url you specified refers back to *this* issue.

**Comment by Napsty** [comment]
That's absolutely correct. You either download the already fixed file (https://github.com/Zomboided/service.vpn.manager/issues/438#issuecomment-3534908935) or you ssh into Kodi and use an editor such as vim or nano and adjust the alternativeNord.py manually (https://github.com/Zomboided/service.vpn.manager/pull/439/files).
I just wanted to mention that it's not a OSMC specific "issue".

**Comment by Rotentilaltondt** [comment]
> Hi All,
> 
> tried everthing above, but cannot get it to work on OSMC Vero, I assume its somthing OSMC specific, however it is still the same error in the log, that the username and PW not found in pass.txt.
> 
> Any Ideas?
> 
> Best regards Steffen

I used @jamakal method for my Vero V (OSMC). It worked immediately after installing his ZIP file, and still works.

**Comment by JSP6668** [comment]
If I got it right, then the api call gets username and a password as response from the api call with the token.
There may be other reasons that cause no response from the api call.
Perhaps DNS or the profile (Germany) that I wanted to use is not valid.

I double checked the alternativeNord.py it is valid including the "Bearer token:" fix.

Thank You for your help!

**Comment by peno64** [comment]
@JSP6668 
Have you tried to generate a new nordvpn token and making sure that it stays valid 'forever' and use that new token?

**Comment by JSP6668** [comment]
Yes I created a token and paste it into ".kodi/userdata/addon_data/service.vpn.manager/settings.xml" to avoid typos.

**Comment by peno64** [comment]
@JSP6668 
And you did it as described here: https://github.com/Zomboided/service.vpn.manager/issues/395

**Comment by Rotentilaltondt** [comment]
> If I got it right, then the api call gets username and a password as response from the api call with the token. There may be other reasons that cause no response from the api call. Perhaps DNS or the profile (Germany) that I wanted to use is not valid.
> 
> I double checked the alternativeNord.py it is valid including the "Bearer token:" fix.
> 
> Thank You for your help!

OSMC, (at least in a Vero) has a sad tendency not to understand that it should delete old information (on the fly) as long as you enter new ones in an additional software. 
Therefore: 
- uninstall VPN manager. Restart Vero. 
- Install VPNmanager again. Restart Vero.
- Download and install @Jamakal's ZIP file.Restart Vero.
- Generate new TOKEN in NordVPN, enter new TOKEN in your profile in VPNManager..and restart Vero

You should now be good to go!

**Comment by JSP6668** [comment]
@Rotentilaltondt 
I will try that it feels like my changes have no effect at all.

**Comment by JSP6668** [comment]
@Rotentilaltondt 
I created a new Token and it worked, Thank You! I don't know why the old one was not accepted.

So it worked finally!

Thank you All!

BR
Steffen

**Comment by zedtech8** [comment]
Looks like openvpn stopped working for Nord again. Tried everything listed above multiple times. Running the latest Libreelec and getting the same error as the first post again. Worked great for months and today no longer works.

**Comment by RobJM2** [comment]
Seems to have stopped here too, tried new token.
Anyone recommend another VPN? Think my renewal is November.

**Comment by dsgdesign** [comment]
Maybe you can try this. I was also having issues with my connection about 2 days ago. I re-checked if my tokens were still there in the add-on and they were unchanged. So this may sound odd, but I went to the add-on Settings-Advanced and applied Potential DNS fix. I did not reboot or change anything. Then I retried my connection with NordVPN and it worked again. It still is working and I am using it every day.

Using Zomboided version 7.04 with NordVPN on OSMC running Kodi 21.2 with a Raspberry Pi.

**Comment by zedtech8** [comment]
It started working again, didn't do anything, maybe an issue on Nords end for tokens maybe?

**Comment by BadIDMan** [comment]
Before I switched to the Wireguard client setup on my Asus router, I created a Kodi add-on that replaced Zomboided OpenVPN and used NordVPN Wireguard mechanism.
Anyone can install this add-on and see how it works.
Please note that I used this add-on about three months ago, so I can't guarantee it works today, and I won't be maintaining/fixing it if any issues are discovered.
Anyone is welcome to download this add-on and continue its development.
https://github.com/BadIDMan/service.wg.monitor

**Comment by zedtech8** [comment]
Thanks will definitely have to try it out
